"""CAG Recipe Generator.

Generates a self-contained ``cag_runtime.py`` file that can be dropped into
any project to load and use a CAG cache without CAM installed.

Used by ``cam cag convert --export-recipe``.
"""
from __future__ import annotations


def generate_recipe(ganglion: str = "imported", knowledge_budget: int = 16000) -> str:
    """Return the full Python source for a standalone cag_runtime.py.

    The generated file has zero external dependencies and contains:
    - ``CAGCache`` class: load, query, stale-mark the corpus
    - ``inject_into_messages()``: prepend corpus into OpenAI-style message list
    - ``build_system_message()``: build a KV-cacheable system message for local LLMs
    - ``__main__`` CLI: ``python cag_runtime.py status|corpus|inject``
    """
    return _RECIPE_TEMPLATE.format(
        ganglion=ganglion,
        knowledge_budget=knowledge_budget,
    )


_RECIPE_TEMPLATE = r'''"""CAG Runtime — standalone Cache-Augmented Generation loader.

Generated by CAM (https://github.com/deesatzed/CAM-Pulse).
Drop this file alongside corpus.txt and meta.json in your project.
Zero external dependencies required.

Usage:
    from cag_runtime import CAGCache, inject_into_messages

    cache = CAGCache()
    cache.load()
    corpus = cache.get_corpus()

    # Option A: Inject into OpenAI-style messages
    messages = [{{"role": "user", "content": "How do I ...?"}}]
    inject_into_messages(corpus, messages)
    # messages[0] is now a system message with the corpus

    # Option B: Build a stable system message for local LLM KV caching
    sys_msg = build_system_message(corpus)
    messages = [{{"role": "system", "content": sys_msg}}, ...]
"""
from __future__ import annotations

import hashlib
import json
import os
import sys
from pathlib import Path

# Defaults baked in at generation time
DEFAULT_GANGLION = "{ganglion}"
DEFAULT_KNOWLEDGE_BUDGET = {knowledge_budget}


class CAGCache:
    """Load and serve a pre-built CAG corpus.

    The cache consists of two files in ``cache_dir/``:
    - ``corpus.txt``  — serialized knowledge base text
    - ``meta.json``   — metadata (document count, build time, stale flag)
    """

    def __init__(
        self,
        cache_dir: str = ".",
        ganglion: str = DEFAULT_GANGLION,
    ) -> None:
        self._cache_dir = Path(cache_dir)
        self._ganglion = ganglion
        self._corpus: str = ""
        self._meta: dict = {{}}

    @property
    def corpus_path(self) -> Path:
        return self._cache_dir / "corpus.txt"

    @property
    def meta_path(self) -> Path:
        return self._cache_dir / "meta.json"

    def load(self) -> bool:
        """Load corpus and metadata from disk. Returns True on success."""
        if not self.corpus_path.exists() or not self.meta_path.exists():
            return False
        try:
            self._corpus = self.corpus_path.read_text(encoding="utf-8")
            self._meta = json.loads(self.meta_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError, UnicodeDecodeError):
            return False
        if not isinstance(self._meta, dict):
            self._meta = {{}}
            return False
        return True

    def is_loaded(self) -> bool:
        """Check if the corpus is loaded in memory."""
        return bool(self._corpus)

    def is_stale(self) -> bool:
        """Check if the cache is marked stale (needs rebuild)."""
        return self._meta.get("stale", True)

    def get_corpus(self) -> str:
        """Return the loaded corpus text. Empty string if not loaded."""
        return self._corpus

    def get_status(self) -> dict:
        """Return cache status as a dict."""
        return {{
            "ganglion": self._ganglion,
            "methodology_count": self._meta.get("methodology_count", 0),
            "built_at": self._meta.get("built_at", None),
            "stale": self._meta.get("stale", True),
            "corpus_tokens_approx": self._meta.get("corpus_tokens_approx", 0),
            "loaded": self.is_loaded(),
            "pointer_count": self._meta.get("pointer_count", 0),
            "shorthand_compression": self._meta.get("shorthand_compression", False),
        }}

    def mark_stale(self) -> None:
        """Mark the cache as stale on disk.

        Call this from any code path that mutates your knowledge base
        (document ingestion, deletion, re-ranking) so the cache is
        rebuilt on next startup.
        """
        self.meta_path.parent.mkdir(parents=True, exist_ok=True)

        meta: dict = {{}}
        if self.meta_path.exists():
            try:
                meta = json.loads(self.meta_path.read_text(encoding="utf-8"))
            except (json.JSONDecodeError, OSError):
                meta = {{}}
        if not isinstance(meta, dict):
            meta = {{}}

        meta["ganglion"] = self._ganglion
        meta["stale"] = True
        self.meta_path.write_text(json.dumps(meta, indent=2), encoding="utf-8")
        self._meta = meta


def inject_into_messages(
    corpus: str,
    messages: list[dict],
    knowledge_budget: int = DEFAULT_KNOWLEDGE_BUDGET,
) -> None:
    """Inject the CAG corpus into an OpenAI-style message list (in place).

    If the first message is a system message, the corpus is appended to it.
    Otherwise a new system message is inserted at position 0.

    Parameters
    ----------
    corpus : str
        The full corpus text from ``CAGCache.get_corpus()``.
    messages : list[dict]
        OpenAI-style ``[{{"role": "...", "content": "..."}}, ...]``.
        Modified in place.
    knowledge_budget : int
        Maximum characters of corpus to inject.
    """
    if not corpus:
        return

    truncated = corpus[:knowledge_budget]
    kb_block = (
        "\n## Knowledge Base\n"
        "The following is your pre-loaded knowledge corpus. "
        "Use these patterns as guidance for your implementation "
        "where applicable.\n\n"
        + truncated
        + "\n\n--- END KNOWLEDGE BASE ---"
    )

    if messages and messages[0].get("role") == "system":
        messages[0]["content"] = messages[0].get("content", "") + kb_block
    else:
        messages.insert(0, {{"role": "system", "content": kb_block}})


def build_system_message(
    corpus: str,
    knowledge_budget: int = DEFAULT_KNOWLEDGE_BUDGET,
) -> str:
    """Build a stable system message for local LLM KV prefix caching.

    The returned string should be used as the ``system`` role message.
    Because it starts with a fixed preamble and the corpus rarely changes,
    local LLM servers (Ollama, llama.cpp, TurboQuant) can cache the KV
    state for this prefix and skip re-computation on subsequent requests.

    Parameters
    ----------
    corpus : str
        The full corpus text.
    knowledge_budget : int
        Maximum characters of corpus to include.

    Returns
    -------
    str
        A complete system message string.
    """
    truncated = corpus[:knowledge_budget] if len(corpus) > knowledge_budget else corpus
    return (
        "You are a knowledge-grounded AI agent. Below is your complete "
        "knowledge base. Use these patterns as authoritative guidance "
        "for all tasks. Do not hallucinate beyond this knowledge.\n\n"
        "=== KNOWLEDGE BASE START ===\n"
        + truncated
        + "\n=== KNOWLEDGE BASE END ==="
    )


def _corpus_hash(corpus: str) -> str:
    """Short hash for cache hit tracking."""
    return hashlib.md5(corpus.encode()).hexdigest()[:12]


# ---------------------------------------------------------------------------
# CLI for quick testing
# ---------------------------------------------------------------------------

def _cli() -> None:
    """Minimal CLI: python cag_runtime.py [status|corpus|inject]"""
    cmd = sys.argv[1] if len(sys.argv) > 1 else "status"

    cache = CAGCache()
    if not cache.load():
        print("ERROR: Could not load corpus.txt + meta.json from current directory.")
        print("Make sure corpus.txt and meta.json are in the same directory as this script.")
        sys.exit(1)

    if cmd == "status":
        status = cache.get_status()
        print(f"Ganglion:       {{status['ganglion']}}")
        print(f"Loaded:         {{status['loaded']}}")
        print(f"Stale:          {{status['stale']}}")
        print(f"Documents:      {{status['methodology_count']}}")
        print(f"Corpus tokens:  {{status['corpus_tokens_approx']:,}}")
        print(f"Built at:       {{status['built_at'] or 'never'}}")

    elif cmd == "corpus":
        print(cache.get_corpus())

    elif cmd == "inject":
        messages = [{{"role": "user", "content": "Hello"}}]
        inject_into_messages(cache.get_corpus(), messages)
        print(json.dumps(messages, indent=2))

    elif cmd == "system-message":
        print(build_system_message(cache.get_corpus()))

    else:
        print(f"Unknown command: {{cmd}}")
        print("Usage: python cag_runtime.py [status|corpus|inject|system-message]")
        sys.exit(1)


if __name__ == "__main__":
    _cli()
'''
